sudo: required
services:
  - docker

before_install:
  - docker build -t dmammarella/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmammarella/react-test npm test

after_success:
  - docker build -t dmammarella/mutli-client ./client
  - docker build -t dmammarella/mutli-nginx ./nginx
  - docker build -t dmammarella/mutli-server ./server
  - docker build -t dmammarella/mutli-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them into docker hub 
  - docker push dmammarella/mutli-client
  - docker push dmammarella/mutli-nginx
  - docker push dmammarella/mutli-server
  - docker push dmammarella/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'Multi-Docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-871365248024'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true